version: "3"
services:
  web:
    build:
      context: ./
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:8082"
    networks:
      - webnet
  websocket:
    build:
      context: ./websocket-server
    volumes:
      - ./websocket-server:/usr/src/app
    ports:
      - "3001:8081"
    networks:
      - webnet
  redis:
    image: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    networks:
      - webnet
networks:
  webnet:
