version: "3"
services:
  web:
    build:
      context: ./
    ports:
      - "3000:8080"
    networks:
      - webnet
  redis:
    image: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    networks:
      - webnet
networks:
  webnet:
